name:                adventofcode2015
version:             0.1.0.0
github:              "scarvalhojr/adventofcode2015"
license:             MIT
author:              "Sergio de Carvalho"
maintainer:          "scarvalhojr@gmail.com"
copyright:           "2021 Sergio de Carvalho"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/scarvalhojr/adventofcode2015#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- cryptonite
- fmt >=0.5 && <0.7
- text >=1.2 && <1.3
- text-show
- utf8-string

library:
  source-dirs: src

executables:
  aoc2015:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode2015

tests:
  adventofcode2015-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode2015
